# Generated by Django 5.1.2 on 2024-10-21 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100)),
                ('dia', models.DateField(help_text='Dia do evento', verbose_name='Dia do evento')),
                ('inicio', models.TimeField(help_text='Inicio', verbose_name='Inicio')),
                ('fim', models.TimeField(help_text='Fim', verbose_name='Fim')),
                ('descricao', models.TextField(blank=True, help_text='Descrição', null=True, verbose_name='Descrição')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
